export const ERROR_MESSAGES = {
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  SOMETHING_WENT_WRONG: "Something went wrong",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  BAD_REQUEST: "Bad Request",
  NOT_FOUND: "Not Found",
  LOGIN_FAILED: "Login failed",
  EMAIL_EXISTS:"Email Already Exists",
  LOGOUT_SUCCESS:"Logot Successfull",

  INVALID_CREDENTIALS: "Invalid email or password",
  PASSWORD_INCORRECT: "Password is incorrect",
  ACCOUNT_BLOCKED: "Your account has been blocked",
  ACCOUNT_NOT_VERIFIED: "Your account is not verified",

  USER_FAILED: "User account creation failed",
  USER_VERIFIED:"User Verified",
  USER_NOT_FOUND: "User Not Found",
  USER_BLOCKED: "User account has been blocked",
  OTP_INVALID: "Invalid or expired OTP",
  RESET_LINK_SENT: "Password reset link sent successfully",
  INVALID_RESET_TOKEN: "Invalid or expired reset token",
  PASSWORD_RESET_SUCCESS: "Password has been reset successfully",
  TRAINER_VERIFIED:"Trainer Verified Successfully",
   TRAINER_FAILED: "Trainer account creation failed",
   TRAINER_NOT_VERIFIED:"Trainer Is Not Verified",
  TRAINER_DECLINED: "Trainer declined and deleted successfully",
  TRAINER_NOT_FOUND: "Trainer Not Found",
  TRAINER_BLOCKED: "Trainer Is Blocked",
  CERTIFICATE_MISSING:"Trainer certificate is required.",

  REFRESH_TOKEN_MISSING: "No refresh token provided",
  REFRESH_TOKEN_INVALID: "Invalid refresh token",
  OTP_FAILED:"Creating Otp Failed",
}
